/*
  ____                                   _             _
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/
# A Template for SiggenPlugin, a Source Plugin
# Generated by the command: plugin -t source -d SigGen_plugin SigGen
# Hostname: Fram-IV
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-09-09T10:44:14.721+0200
# NOTICE: MADS Version 2.4.3
*/
// Mandatory included headers
#include <source.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include <siggen.hpp>

#include <chrono>
#include <cmath>
#include <exception>
#include <memory>
#include <numbers>
#include <set>
#include <sstream>
#include <string>
#include <vector>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "signals"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

namespace {

/// Keys of the settings section that belong to the agent or to the plugin
/// itself. Everything else is copied into the document handed to SigGen, so
/// that a signal may refer to it as an algebraic expression ("$f0 * 3").
const set<string> ReservedKeys = {
    // consumed by the plugin
    "signals", "sample_rate", "seed", "nest", "track_period", "epoch",
    // injected by the host
    "agent_id", "agent_name", "prefix",
    // consumed by the agent
    "period", "pub_topic", "sub_topic", "receive_timeout", "dont_block",
    "wire_format", "compression", "queue_size", "driver", "attachment",
    "attachment_ext", "clock_source", "clock_sync_responder", "time_step",
    "time_step_us", "high_res_loop", "spin_margin_us", "dummy"};

/// Default loop period of the source agent, in milliseconds: the fallback
/// when the settings carry neither "sample_rate" nor "period".
constexpr double DefaultPeriodMs = 100.0;

/// Number of initial calls during which any measured period is accepted, and
/// the weight of a new measurement in the running estimate afterwards.
constexpr unsigned WarmupCalls = 5;
constexpr double Smoothing = 0.2;

string format_number(double value) {
  ostringstream os;
  os << value;
  return os.str();
}

} // namespace


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class SignalsPlugin : public Source<json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Source::Source; // inherit constructors

  // Typically, no need to change this: PLUGIN_NAME is defined by the build
  // system from the target name, and the host looks the driver up by that name.
  // Since protocol P8 kind() no longer selects the settings section (the agent
  // name does); it is checked against the driver name and a mismatch is a
  // startup warning.
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types (full per-host semantics:
  //  .claude/skills/mads-plugin/reference/return-types.md):
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result before publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    (void)blob; // this source publishes JSON only
    out.clear();

    // A configuration that could not be turned into generators is not
    // recoverable: set_params() cannot report it, so the first call does.
    if (!_setup_error.empty()) {
      _error = _setup_error;
      return return_type::critical;
    }

    try {
      // The signal values, as a name -> value map. Written into `out` after
      // "t" and "n" below, so that a signal named "t" or "n" wins over them.
      json values = json::object();

      if (_synchro) {
        // Address the sample belonging to *now* rather than counting calls:
        // every plugin sharing the epoch, sample rate and seed lands on the
        // same index at the same wall-clock instant, however far apart each
        // of them started.
        const double now = SigGen::unix_now();
        const uint64_t index = _generators.front().signals.front()->index_at(now);
        out["t"] = _generators.front().signals.front()->time_at(index);
        out["n"] = index;
        out["sample_rate"] = _sample_rate;
        for (auto &generator : _generators)
          values[generator.name] = sample_generator(generator, index);
      } else {
        // One sample per call means the sampling frequency is the reciprocal
        // of the loop period; keep it aligned with the period actually
        // observed.
        track_call_period();
        out["t"] = _elapsed;
        out["n"] = _index;
        out["sample_rate"] = _sample_rate;
        for (auto &generator : _generators)
          values[generator.name] = sample_generator(generator, 0);
        _elapsed += 1.0 / _sample_rate;
        _index += 1;
      }

      if (_nest.empty())
        out.update(values);
      else
        out[_nest] = values;
    } catch (const exception &e) {
      _error = string("signal generation failed: ") + e.what();
      return return_type::error;
    }

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }

  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters
    // (e.g. agent_id, etc.)
    Source::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["signals"] = json::object(); // name -> SigGen signal description
    _params["sample_rate"] = nullptr;    // Hz, default: 1000 / period
    _params["seed"] = nullptr;           // base seed, default: non-reproducible
    _params["nest"] = "";                // key holding the map, "" = flat
    _params["track_period"] = true;      // follow the measured call period
    _params["epoch"] = 0.0;              // shared Unix-s epoch; 0 = no synchro
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

    // Build the generators once, here: get_output() must stay allocation- and
    // parse-free. A failure is stored and reported by the first call.
    _setup_error.clear();
    _elapsed = 0.0;
    _index = 0;
    _calls = 0;
    _dt = 0.0;
    try {
      _nest = _params["nest"].get<string>();
      _track_period = _params["track_period"].get<bool>();
      _epoch = resolve_epoch();
      _synchro = _epoch != 0.0;
      _sample_rate = resolve_sample_rate();
      if (_synchro && _track_period) {
        // A per-instance measured period would let cooperating plugins drift
        // to different sampling rates, which breaks the very alignment synchro
        // generation is for: the epoch, the rate and the seed must all be
        // identical across them.
        _track_period = false;
        _rate_source += "; frozen for synchro generation";
      }
      build_generators();
    } catch (const exception &e) {
      _setup_error = e.what();
      _generators.clear();
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    if (!_setup_error.empty())
      return {{"ERROR", _setup_error}};

    ostringstream names;
    for (size_t i = 0; i < _generators.size(); ++i) {
      names << (i ? ", " : "") << _generators[i].name << " (";
      for (size_t j = 0; j < _generators[i].signals.size(); ++j)
        names << (j ? "+" : "") << _generators[i].signals[j]->type();
      names << ")";
    }

    return {
        {"signals", names.str()},
        {"sample rate", format_number(_sample_rate) + " Hz (" + _rate_source + ")"},
        {"track call period", _track_period ? "yes" : "no"},
        {"seed", _seeded ? std::to_string(_seed) : "random"},
        {"output map", _nest.empty() ? "flat" : _nest},
        {"synchro epoch",
         _synchro ? format_number(_epoch) + " (unix s)" : "disabled"},
    };
  };

private:
  // Define the fields that are used to store internal resources
  //
  // Normally one signal per name, published as a scalar; a "signals" entry
  // given as a JSON array builds one generator per element instead, and
  // sample_generator() packs their values into a JSON array in that order --
  // e.g. a 3-element "position" publishes {"position": [x, y, z]}.
  struct Generator {
    string name;
    vector<unique_ptr<SigGen::Signal>> signals;
  };

  /// One sample from every underlying generator behind `generator`, as a
  /// scalar for an ordinary entry or a JSON array, in declaration order, for
  /// one built from an array of signal descriptions.
  json sample_generator(Generator &generator, uint64_t index) {
    if (generator.signals.size() == 1) {
      SigGen::Signal &signal = *generator.signals.front();
      return _synchro ? signal.at(index) : signal.next();
    }
    json values = json::array();
    for (auto &signal : generator.signals)
      values.push_back(_synchro ? signal->at(index) : signal->next());
    return values;
  }

  /// The shared epoch for synchro generation, in seconds since the Unix
  /// epoch. Zero (the default) means every generator is addressed the usual
  /// way, one next() per call, with no cross-plugin alignment.
  double resolve_epoch() {
    const json &epoch = _params["epoch"];
    if (!epoch.is_number())
      throw runtime_error("'epoch' must be a number, got " +
                          string(epoch.type_name()));
    return epoch.get<double>();
  }

  /// The sampling frequency: an explicit "sample_rate" wins, otherwise it is
  /// the reciprocal of the agent loop period.
  double resolve_sample_rate() {
    const json &rate = _params["sample_rate"];
    if (!rate.is_null()) {
      if (!rate.is_number())
        throw runtime_error("'sample_rate' must be a number, got " +
                            string(rate.type_name()));
      const double fs = rate.get<double>();
      if (!(fs > 0.0))
        throw runtime_error("'sample_rate' must be positive, got " +
                            format_number(fs));
      // An explicit rate is a deliberate choice: don't second-guess it with
      // the measured one.
      _track_period = false;
      _rate_source = "from sample_rate";
      return fs;
    }

    double period_ms = DefaultPeriodMs;
    _rate_source = "assuming the default period of " + format_number(period_ms) +
                   " ms";
    const auto it = _params.find("period");
    if (it != _params.end() && it->is_number() && it->get<double>() > 0.0) {
      period_ms = it->get<double>();
      _rate_source = "from period = " + format_number(period_ms) + " ms";
    }
    return 1000.0 / period_ms;
  }

  /// Build one SigGen signal from an already-scoped descriptor: `base` plus
  /// the descriptor under "signal", the section's sample rate and epoch, and
  /// the next derived seed. `offset` is shared across every signal built for
  /// the section, scalar or grouped, so each still gets its own stream.
  unique_ptr<SigGen::Signal> build_component(const json &base,
                                             const json &descriptor,
                                             uint64_t &offset) {
    if (!descriptor.is_object())
      throw runtime_error("expected a signal object, got " +
                          string(descriptor.type_name()));

    json document = base;
    document["signal"] = descriptor;
    document["sample_rate"] = _sample_rate;
    document["epoch"] = _epoch;
    // Distinct streams: sharing one seed would make every signal's noise the
    // same sequence. A per-signal "seed" overrides the derived one.
    if (descriptor.contains("seed"))
      document["seed"] = descriptor["seed"];
    else if (_seeded)
      document["seed"] = _seed + offset;
    offset += 1;

    auto signal = SigGen::from_json(document);
    // Synchro generation addresses samples by index (see get_output()),
    // which not every generator can do; refuse to start rather than
    // silently falling back to an unsynchronized stream.
    if (_synchro && !signal->is_addressable())
      throw runtime_error("type '" + signal->type() +
                          "' does not support synchro generation (not "
                          "addressable); set 'epoch' to 0 to drop it");
    return signal;
  }

  /// Turn the "signals" map into generators, one per entry.
  ///
  /// An entry is either a single signal description (published as a scalar)
  /// or a JSON array of them (published as a JSON array in that order, e.g.
  /// a 3-element "position" for an [x, y, z] reading). Either way, each
  /// underlying signal is built from a document made of the whole settings
  /// section minus the reserved keys, with the signal itself under "signal":
  /// that is what lets a description refer to a section-level constant as
  /// "$f0", the way a stand-alone SigGen configuration file does.
  void build_generators() {
    _generators.clear();

    const json &signals = _params["signals"];
    if (!signals.is_object())
      throw runtime_error("'signals' must be an object, got " +
                          string(signals.type_name()));
    if (signals.empty())
      throw runtime_error("no signals configured: add a "
                          "[<agent>.signals.<name>] table for each signal");

    json base = json::object();
    for (const auto &item : _params.items()) {
      // Objects would be read as signal descriptions, and the reserved keys
      // are none of SigGen's business.
      if (ReservedKeys.count(item.key()) || item.value().is_object())
        continue;
      base[item.key()] = item.value();
    }

    _seeded = _params["seed"].is_number_unsigned();
    if (_seeded)
      _seed = _params["seed"].get<uint64_t>();
    else if (!_params["seed"].is_null())
      throw runtime_error("'seed' must be a non-negative integer, got " +
                          string(_params["seed"].type_name()));

    uint64_t offset = 0;
    for (const auto &item : signals.items()) {
      vector<unique_ptr<SigGen::Signal>> group;
      try {
        if (item.value().is_array()) {
          if (item.value().empty())
            throw runtime_error("an array of signals must not be empty");
          for (const auto &descriptor : item.value())
            group.push_back(build_component(base, descriptor, offset));
        } else {
          group.push_back(build_component(base, item.value(), offset));
        }
      } catch (const exception &e) {
        throw runtime_error("signal '" + item.key() + "': " + e.what());
      }
      _generators.push_back({item.key(), std::move(group)});
    }
  }

  /// Follow the period at which the host actually calls us, so that the
  /// sampling frequency stays the reciprocal of the loop period even when it
  /// is set with -p, which the plugin cannot read from the settings.
  void track_call_period() {
    if (!_track_period)
      return;
    const auto now = chrono::steady_clock::now();
    if (_calls > 0) {
      const double dt = chrono::duration<double>(now - _last_call).count();
      // Ignore a stalled or bunched-up iteration, but only once the estimate
      // has settled: during the warm-up every measurement is informative.
      const bool plausible =
          dt > 0.0 && (_dt <= 0.0 || _calls <= WarmupCalls ||
                       (dt > 0.25 * _dt && dt < 4.0 * _dt));
      if (plausible)
        _dt = _dt <= 0.0 ? dt : (1.0 - Smoothing) * _dt + Smoothing * dt;
      if (_dt > 0.0)
        update_sample_rate(1.0 / _dt);
    }
    _last_call = now;
    _calls += 1;
  }

  /// Propagate a new sampling frequency to every generator, skipping changes
  /// too small to matter.
  void update_sample_rate(double fs) {
    if (!(fs > 0.0) || fabs(fs - _sample_rate) <= 1e-3 * _sample_rate)
      return;
    _sample_rate = fs;
    for (auto &generator : _generators)
      for (auto &signal : generator.signals)
        signal->set_sample_rate(fs);
  }

  vector<Generator> _generators;
  string _setup_error;
  string _rate_source;
  string _nest;
  double _sample_rate = 1000.0 / DefaultPeriodMs;
  double _elapsed = 0.0;
  uint64_t _index = 0;
  uint64_t _seed = 0;
  bool _seeded = false;
  bool _track_period = true;
  double _epoch = 0.0;
  bool _synchro = false;
  // call-period tracking
  chrono::steady_clock::time_point _last_call;
  double _dt = 0.0;
  unsigned _calls = 0;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
MADS_REGISTER_PLUGINS(SignalsPlugin)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
namespace {

int Failures = 0;

void check(bool condition, const string &what) {
  if (!condition) {
    cerr << "FAIL: " << what << endl;
    Failures += 1;
  }
}

void check_close(double actual, double expected, const string &what) {
  check(fabs(actual - expected) < 1e-9,
        what + " (expected " + format_number(expected) + ", got " +
            format_number(actual) + ")");
}

/// A configuration with a fixed sampling rate, hence a deterministic one:
/// an explicit sample_rate switches the call-period tracking off.
json base_params() {
  json params;
  params["sample_rate"] = 8.0;
  params["f0"] = 1.0;
  params["signals"]["sine"] = {{"type", "sine"},   {"frequency", "$f0"},
                               {"amplitude", 2.0}, {"offset", 1.0},
                               {"noiseless", true}};
  params["signals"]["ramp"] = {{"type", "sawtooth"},
                               {"frequency", "$f0 / 2"},
                               {"amplitude", 1.0},
                               {"noiseless", true}};
  return params;
}

/// The waveform the plugin is expected to reproduce, sample by sample.
double expected_sine(uint64_t n) {
  return 2.0 * sin(2.0 * std::numbers::pi * fmod(n * 1.0 / 8.0, 1.0)) + 1.0;
}

double expected_ramp(uint64_t n) {
  return 2.0 * fmod(n * 0.5 / 8.0, 1.0) - 1.0;
}

void test_waveforms() {
  SignalsPlugin plugin;
  plugin.set_params(base_params());

  json out;
  for (uint64_t n = 0; n < 16; ++n) {
    check(plugin.get_output(out) == return_type::success,
          "get_output() succeeds at sample " + std::to_string(n));
    check(out.contains("sine") && out.contains("ramp"),
          "both signals are present in the frame");
    check_close(out["t"].get<double>(), n / 8.0, "time of sample");
    check(out["n"].get<uint64_t>() == n, "index of sample");
    check_close(out["sample_rate"].get<double>(), 8.0, "sampling rate");
    check_close(out["sine"].get<double>(), expected_sine(n),
                "sine at sample " + std::to_string(n));
    check_close(out["ramp"].get<double>(), expected_ramp(n),
                "sawtooth at sample " + std::to_string(n));
  }

  cout << "Output: " << out << endl;
}

void test_nested_output() {
  SignalsPlugin plugin;
  json params = base_params();
  params["nest"] = "values";
  plugin.set_params(params);

  json out;
  check(plugin.get_output(out) == return_type::success, "nested run succeeds");
  check(out["values"].is_object() && out["values"].size() == 2,
        "the values are nested under 'values'");
  check(!out.contains("sine"), "nothing is published at the top level");
  check_close(out["values"]["sine"].get<double>(), expected_sine(0),
              "nested sine sample");
}

void test_sample_rate_from_period() {
  SignalsPlugin plugin;
  json params = base_params();
  params.erase("sample_rate");
  params["period"] = 250; // ms, i.e. 4 Hz
  params["track_period"] = false;
  plugin.set_params(params);

  json out;
  check(plugin.get_output(out) == return_type::success, "period-driven run");
  check_close(out["sample_rate"].get<double>(), 4.0,
              "sampling rate derived from the loop period");
}

void test_seeding() {
  json params = base_params();
  params["seed"] = 20260909u;
  params["signals"]["noise_a"] = {{"type", "white_noise"}, {"sigma", 1.0}};
  params["signals"]["noise_b"] = {{"type", "white_noise"}, {"sigma", 1.0}};

  SignalsPlugin one, two;
  one.set_params(params);
  two.set_params(params);

  json out_one, out_two;
  for (int i = 0; i < 4; ++i) {
    one.get_output(out_one);
    two.get_output(out_two);
    check(out_one == out_two, "the same seed gives the same frame");
    check(out_one["noise_a"] != out_one["noise_b"],
          "each signal gets its own random stream");
  }
}

/// Two plugin instances sharing an epoch, sample rate and (implicitly, since
/// both signals are noiseless waveforms) no randomness must agree on every
/// sample: get_output() addresses whatever index "now" belongs to, rather
/// than counting its own calls, so neither instance's history matters.
void test_synchro_generation() {
  json params = base_params();
  params["epoch"] = 1'700'000'000.0; // an arbitrary shared reference instant

  SignalsPlugin one, two;
  one.set_params(params);
  two.set_params(params);

  json out_one, out_two;
  for (int i = 0; i < 4; ++i) {
    check(one.get_output(out_one) == return_type::success,
          "synchro run succeeds on the first instance");
    check(two.get_output(out_two) == return_type::success,
          "synchro run succeeds on the second instance");
    check(out_one == out_two,
          "two independently started plugins agree on the same wall-clock sample");
  }
}

/// A signal that cannot be addressed by index must stop synchro generation
/// from starting at all, rather than silently falling back to next().
void test_synchro_requires_addressable() {
  json params = base_params();
  params["epoch"] = 1'700'000'000.0;
  params["signals"]["walk"] = {
      {"type", "arima"}, {"ar", json::array({0.6})}, {"d", 1}};

  SignalsPlugin plugin;
  plugin.set_params(params);

  json out;
  check(plugin.get_output(out) == return_type::critical,
        "a non-addressable signal refuses to start under synchro generation");
  check(plugin.error().find("addressable") != string::npos,
        "the error explains that the signal cannot be addressed");
}

/// A "signals" entry given as a JSON array builds one generator per element
/// and packs their values into a JSON array, in declaration order, under
/// that one key -- e.g. for a position reading published as [x, y, z].
void test_signal_group() {
  SignalsPlugin plugin;
  json params = base_params();
  params["signals"]["position"] = json::array(
      {{{"type", "sine"},
        {"frequency", "$f0"},
        {"amplitude", 2.0},
        {"offset", 1.0},
        {"noiseless", true}},
       {{"type", "sawtooth"},
        {"frequency", "$f0 / 2"},
        {"amplitude", 1.0},
        {"noiseless", true}}});
  plugin.set_params(params);

  json out;
  for (uint64_t n = 0; n < 4; ++n) {
    check(plugin.get_output(out) == return_type::success,
          "a grouped run succeeds at sample " + std::to_string(n));
    check(out["position"].is_array() && out["position"].size() == 2,
          "the group is published as an array, in declaration order");
    check_close(out["position"][0].get<double>(), expected_sine(n),
                "first component of the group at sample " + std::to_string(n));
    check_close(out["position"][1].get<double>(), expected_ramp(n),
                "second component of the group at sample " + std::to_string(n));
  }
}

/// Every element of a group is built the same way a scalar entry is, so it
/// gets its own derived seed and hence its own random stream.
void test_signal_group_independent_streams() {
  json params = base_params();
  params["seed"] = 20260910u;
  params["signals"]["pair"] = json::array(
      {{{"type", "white_noise"}, {"sigma", 1.0}},
       {{"type", "white_noise"}, {"sigma", 1.0}}});

  SignalsPlugin plugin;
  plugin.set_params(params);

  json out;
  plugin.get_output(out);
  check(out["pair"][0] != out["pair"][1],
        "each element of a group gets its own random stream");
}

/// An empty array names a real mistake -- a group with nothing in it -- and
/// is refused rather than silently publishing an empty array forever.
void test_signal_group_empty_is_critical() {
  SignalsPlugin plugin;
  json params = base_params();
  params["signals"]["nothing"] = json::array();
  plugin.set_params(params);

  json out;
  check(plugin.get_output(out) == return_type::critical,
        "an empty group is critical");
  check(plugin.error().find("nothing") != string::npos,
        "the error names the offending signal");
}

void test_configuration_errors() {
  json out;

  SignalsPlugin empty;
  empty.set_params(json{{"sample_rate", 8.0}});
  check(empty.get_output(out) == return_type::critical,
        "an empty configuration is critical");
  check(empty.info().count("ERROR") == 1, "info() reports the failure");

  SignalsPlugin unknown;
  json params = base_params();
  params["signals"]["sine"]["type"] = "no_such_signal";
  unknown.set_params(params);
  check(unknown.get_output(out) == return_type::critical,
        "an unknown signal type is critical");
  check(unknown.error().find("sine") != string::npos,
        "the error names the offending signal");

  SignalsPlugin broken;
  params = base_params();
  params["signals"]["sine"]["frequency"] = "$nowhere";
  broken.set_params(params);
  check(broken.get_output(out) == return_type::critical,
        "an unresolved expression is critical");
}

} // namespace

int main(int argc, char const *argv[]) {
  (void)argc;
  (void)argv;

  test_waveforms();
  test_nested_output();
  test_sample_rate_from_period();
  test_seeding();
  test_synchro_generation();
  test_synchro_requires_addressable();
  test_signal_group();
  test_signal_group_independent_streams();
  test_signal_group_empty_is_critical();
  test_configuration_errors();

  if (Failures > 0) {
    cerr << Failures << " check(s) failed" << endl;
    return 1;
  }
  cout << "All checks passed" << endl;
  return 0;
}
